version: "2.2"
services:
  jgw:
    build:
      context: java
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55555:55555

  iris:
    init: true
    build:
      context: iris
      dockerfile: Dockerfile
    depends_on:
      - 'jgw'
    ports:
      - 52773:52773
      - 51773:51773
